# Generated by Django 4.1.3 on 2022-11-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
