# Generated by Django 4.1.3 on 2022-11-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=16, unique=True, verbose_name='Username'),
        ),
    ]
